### ISSUE TITLE
connection.js not looking at .env credentials

### ISSUE THREAD

**Issue by yeo-yeo** [fac19/week5-cjhk#41]
I think there's one tiny thing missing from connection.js!  For the postgres database connection to work, it needs to be pointed to the right value in your environment variables - I think you're missing something like line 7 below

This may also be causing your problem on Heroku - at the moment the site is unable to query the database because it doesn't know where to look :)

![image](https://user-images.githubusercontent.com/28454190/78339577-98f0a380-758c-11ea-821c-47f7a6ddcbca.png)

![gif](https://media.giphy.com/media/26n6WywJyh39n1pBu/giphy.gif)

**Comment by oliverjam** [comment]
More explanation of that here: https://github.com/oliverjam/postgres-boilerplate/#databaseconnectionjs

**Comment by oliverjam** [comment]
Great GitHub workflow on this one team! Labels, project board tracking, assignment, referenced issue in a commit, PR, done 😍

**Comment by Alexreid95** [comment]
Thanks guys this worked!!! It's working on heroku now!!!
