### ISSUE TITLE
core learning objectives met

### ISSUE THREAD

**Issue by yeo-yeo** [fac19/week5-cjhk#43]
You've built a database which can be queried from a webpage, and added to with a form.  Nice work!!! It's not easy!!

![gif](https://media.giphy.com/media/6oMKugqovQnjW/giphy.gif)

**Comment by yeo-yeo** [comment]
genuinely mean the it's not easy part... when i was asked to code review this week i was terrified because i can never remember how to set up the PG stuff

**Comment by glrta** [comment]
Good job on getting it to work! Keeping it to one table must have made a difference. Nice job!
