### ISSUE TITLE
finish up readme

### ISSUE THREAD

**Issue by yeo-yeo** [fac19/week5-cjhk#45]
I found your setup instructions really helpful - thank you!  One more thing you could add is creating the .env in the root file, and the format for the database url value.

Don't forget to add your db scema as well if you get a chance.  There are sites you can use to create diagrams for you, e.g. https://dbdiagram.io/

**Comment by oliverjam** [comment]
A helpful thing to do is create a file named something like `example.env` (so it isn't gitignored) with example env variables in it. That way it's easy for someone cloning the repo to rename the file to `.env` and replace the example variables with their own.
